name: Deploy to Firebase
on: workflow_dispatch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install web dependencies
        run: npm ci
        working-directory: web

      - name: Install functions dependencies
        run: npm ci
        working-directory: functions

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
          projectId: ${{ vars.FIREBASE_PROJECT_ID }}
