name: Deploy to Firebase
on: workflow_dispatch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install web dependencies
        run: npm ci
        working-directory: web

      - name: Install functions dependencies
        run: npm ci
        working-directory: functions

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
          PROJECT_ID: open-ics
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_OPEN_ICS }}
