name: Update Dependencies
on: workflow_dispatch

jobs:
  update-web:
    uses: RMHAM/co-ares-catalog/.github/workflows/update-web.yml@main
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}

  update-func:
    uses: RMHAM/co-ares-catalog/.github/workflows/update-func.yml@main
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}

  update-firestore:
    uses: RMHAM/co-ares-catalog/.github/workflows/update-firestore.yml@main
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
